/**
 * Maps ARK creature identifiers to Gigasaurus API slugs.
 *
 * Two lookup strategies, tried in order:
 *   1. DinoNameTag (the short game tag, e.g. "Rex", "Yutyrannus")
 *   2. DinoClass blueprint path (last path segment before the dot)
 *
 * Returns null when the creature has no matching entry in our API.
 */

// ─── DinoNameTag → slug ────────────────────────────────────────────────────────

const NAME_TAG_MAP: Record<string, string> = {
  // Dinosaurs
  Allo: 'allosaurus',
  Allosaurus: 'allosaurus',
  Amarg: 'amargasaurus',
  Amargasaurus: 'amargasaurus',
  Anky: 'ankylosaurus',
  Ankylosaurus: 'ankylosaurus',
  Archa: 'archaeopteryx',
  Archaeopteryx: 'archaeopteryx',
  Barry: 'baryonyx',
  Baryonyx: 'baryonyx',
  Bronto: 'brontosaurus',
  Brontosaurus: 'brontosaurus',
  Carcha: 'carcharodontosaurus',
  Carcharodontosaurus: 'carcharodontosaurus',
  Carno: 'carnotaurus',
  Carnotaurus: 'carnotaurus',
  Compy: 'compy',
  Deinonychus: 'deinonychus',
  Dilo: 'dilophosaur',
  Dilophosaur: 'dilophosaur',
  Diplo: 'diplodocus',
  Diplodocus: 'diplodocus',
  Dreadnoughtus: 'dreadnoughtus',
  Galli: 'gallimimus',
  Gallimimus: 'gallimimus',
  Gigant: 'giganotosaurus',
  Giganotosaurus: 'giganotosaurus',
  Gigantoraptor: 'gigantoraptor',
  Iguanodon: 'iguanodon',
  Kent: 'kentrosaurus',
  Kentrosaurus: 'kentrosaurus',
  Mega: 'megalosaurus',
  Megalosaurus: 'megalosaurus',
  Microraptor: 'microraptor',
  Oviraptor: 'oviraptor',
  Pachy: 'pachy',
  PachyRhino: 'pachyrhinosaurus',
  Pachyrhinosaurus: 'pachyrhinosaurus',
  Para: 'parasaur',
  Parasaur: 'parasaur',
  Pegomastax: 'pegomastax',
  Raptor: 'raptor',
  Rex: 'rex',
  Spino: 'spino',
  Stego: 'stegosaurus',
  Stegosaurus: 'stegosaurus',
  Theri: 'therizinosaur',
  Therizino: 'therizinosaur',
  Therizinosaur: 'therizinosaur',
  Titanosaur: 'titanosaur',
  Trike: 'triceratops',
  Triceratops: 'triceratops',
  Troodon: 'troodon',
  Yutyrannus: 'yutyrannus',
  YiLing: 'yi_ling',
  // Fantasy / aberration / DLC
  Astrocetus: 'astrocetus',
  Astrodelphis: 'astrodelphis',
  Basilisk: 'basilisk',
  Bloodstalker: 'bloodstalker',
  Bulbdog: 'bulbdog',
  CrystalWyvern: 'crystal_wyvern',
  Deathworm: 'deathworm',
  FeatherLight: 'featherlight',
  Fenrir: 'fenrir',
  Ferox: 'ferox',
  Gacha: 'gacha',
  Gasbags: 'gasbags',
  Glowtail: 'glowtail',
  Griffin: 'griffin',
  InsectSwarm: 'insect_swarm',
  CaveCrab: 'karkinos',
  Karkinos: 'karkinos',
  Macrophage: 'macrophage',
  Maewing: 'maewing',
  Magmasaur: 'magmasaur',
  Managarmr: 'managarmr',
  Megachelon: 'megachelon',
  Morellatops: 'morellatops',
  Nameless: 'nameless',
  Noglin: 'noglin',
  ParakeetFishSchool: 'parakeet_fish_school',
  Phoenix: 'phoenix',
  Ravager: 'ravager',
  Reaper: 'reaper',
  RockDrake: 'rock_drake',
  RockGolem: 'rock_elemental',
  RockElemental: 'rock_elemental',
  Seeker: 'seeker',
  Shadowmane: 'shadowmane',
  Shinehorn: 'shinehorn',
  Owl: 'snow_owl',
  SnowOwl: 'snow_owl',
  Summoner: 'summoner',
  Unicorn: 'unicorn',
  Equus: 'equus',
  Velonasaur: 'velonasaur',
  Wyvern: 'wyvern',
  // Newly scraped creatures
  // Birds
  Argent: 'argentavis',
  Argentavis: 'argentavis',
  Dimorph: 'dimorphodon',
  Dimorphodon: 'dimorphodon',
  Fjordhawk: 'fjordhawk',
  Hesperornis: 'hesperornis',
  Ichthyornis: 'ichthyornis',
  Kairuku: 'kairuku',
  Pelo: 'pelagornis',
  Pelagornis: 'pelagornis',
  Ptero: 'pteranodon',
  Pteranodon: 'pteranodon',
  Quetzal: 'quetzal',
  Sinomacrops: 'sinomacrops',
  Tapejara: 'tapejara',
  TerrorBird: 'terror_bird',
  Tropeognathus: 'tropeognathus',
  Vulture: 'vulture',
  // Mammals
  Andrewsarchus: 'andrewsarchus',
  Castoroides: 'castoroides',
  Chalico: 'chalicotherium',
  Chalicotherium: 'chalicotherium',
  Daeodon: 'daeodon',
  Deinotherium: 'deinotherium',
  Direbear: 'dire_bear',
  DireBear: 'dire_bear',
  Dire_Bear: 'dire_bear',
  Direwolf: 'direwolf',
  Gigantopithecus: 'gigantopithecus',
  Hyaenodon: 'hyaenodon',
  Jerboa: 'jerboa',
  Lystrosaurus: 'lystrosaurus',
  Mammoth: 'mammoth',
  Meso: 'mesopithecus',
  Mesopithecus: 'mesopithecus',
  Otter: 'otter',
  Ovis: 'ovis',
  Paracer: 'paraceratherium',
  Paraceratherium: 'paraceratherium',
  Phiomia: 'phiomia',
  Procoptodon: 'procoptodon',
  Procoptdon: 'procoptodon',
  Purlovia: 'purlovia',
  Rhino: 'woolly_rhino',
  WoollyRhino: 'woolly_rhino',
  Thylacoleo: 'thylacoleo',
  // Reptiles / amphibians
  Beelzebufo: 'beelzebufo',
  Carbo: 'carbonemys',
  Carbonemys: 'carbonemys',
  Ceratosaurus: 'ceratosaurus',
  Deinosuchus: 'deinosuchus',
  Diplocaulus: 'diplocaulus',
  Sarco: 'sarco',
  Sarcosuchus: 'sarco',
  // Fish / aquatics
  Angler: 'anglerfish',
  Anglerfish: 'anglerfish',
  Basilo: 'basilosaurus',
  Basilosaurus: 'basilosaurus',
  Chrysaora: 'chrysaora',
  Cnidaria: 'cnidaria',
  Coel: 'coelacanth',
  Coelacanth: 'coelacanth',
  Dunkle: 'dunkleosteus',
  Dunkleosteus: 'dunkleosteus',
  Electrophorus: 'electrophorus',
  Eurypterid: 'eurypterid',
  Helicoprion: 'helicoprion',
  Ichthyo: 'ichthyosaurus',
  Ichthyosaurus: 'ichthyosaurus',
  Leedsichthys: 'leedsichthys',
  Liopleurodon: 'liopleurodon',
  Manta: 'manta',
  Megalodon: 'megalodon',
  Mosa: 'mosasaurus',
  Mosasaurus: 'mosasaurus',
  Piranha: 'piranha',
  Plesiosaur: 'plesiosaur',
  SabertoothSalmon: 'sabertooth_salmon',
  Tusoteuthis: 'tusoteuthis',
  // Invertebrates / insects
  Achatina: 'achatina',
  Ammonite: 'ammonite',
  Arthro: 'arthropluera',
  Arthropluera: 'arthropluera',
  GiantBee: 'giant_bee',
  Glowbug: 'glowbug',
  JugBug: 'jug_bug',
  Lamprey: 'lamprey',
  Leech: 'leech',
  Lymantria: 'lymantria',
  Meganeura: 'meganeura',
  Onyc: 'onyc',
  Scorpion: 'pulmonoscorpius',
  Pulmonoscorpius: 'pulmonoscorpius',
  Titanomyrma: 'titanomyrma',
  Trilobite: 'trilobite',
  // Additional dinosaurs
  Cryolophosaurus: 'cryolophosaurus',
  Desmodus: 'desmodus',
  Dimetro: 'dimetrodon',
  Dimetrodon: 'dimetrodon',
  Dinopithecus: 'dinopithecus',
  Dodo: 'dodo',
  Doed: 'doedicurus',
  Doedicurus: 'doedicurus',
  DungBeetle: 'dung_beetle',
  Fasolasuchus: 'fasolasuchus',
  Kapro: 'kaprosuchus',
  Kaprosuchus: 'kaprosuchus',
  Maeguana: 'maeguana',
  Mantis: 'mantis',
  Megalania: 'megalania',
  Megaloceros: 'megaloceros',
  Megatherium: 'megatherium',
  RollRat: 'roll_rat',
  Rollrat: 'roll_rat',
  Saber: 'sabertooth',
  Sabertooth: 'sabertooth',
  Thorny: 'thorny_dragon',
  Titanoboa: 'titanoboa',
  // DLC / newer
  Archelon: 'archelon',
  Malwyn: 'malwyn',
  Rhyniognatha: 'rhyniognatha',
  Rollrat_Roll: 'roll_rat',
}

// ─── Blueprint class path → slug ───────────────────────────────────────────────

// Extracted from the last path segment: "Rex_Character_BP_C" → "Rex"
// Maps partial class name substrings to slugs as a fallback.
const CLASS_FRAGMENT_MAP: Array<[RegExp, string]> = [
  [/Allosaurus/i, 'allosaurus'],
  [/Amargasaurus/i, 'amargasaurus'],
  [/Ankylosaurus/i, 'ankylosaurus'],
  [/Archaeopteryx/i, 'archaeopteryx'],
  [/Baryonyx/i, 'baryonyx'],
  [/Brontosaurus/i, 'brontosaurus'],
  [/Carcharodontosaurus/i, 'carcharodontosaurus'],
  [/Carnotaurus/i, 'carnotaurus'],
  [/Compy/i, 'compy'],
  [/Deinonychus/i, 'deinonychus'],
  [/Dilophosaur/i, 'dilophosaur'],
  [/Diplodocus/i, 'diplodocus'],
  [/Dreadnoughtus/i, 'dreadnoughtus'],
  [/Gallimimus/i, 'gallimimus'],
  [/Gigantopithecus/i, 'gigantopithecus'],
  [/Giganotosaurus/i, 'giganotosaurus'],
  [/Gigantoraptor/i, 'gigantoraptor'],
  [/Iguanodon/i, 'iguanodon'],
  [/Kentrosaurus/i, 'kentrosaurus'],
  [/Megalosaurus/i, 'megalosaurus'],
  [/Microraptor/i, 'microraptor'],
  [/Oviraptor/i, 'oviraptor'],
  [/Pachyrhinosaurus/i, 'pachyrhinosaurus'],
  [/Pachy/i, 'pachy'],
  [/Parasaur/i, 'parasaur'],
  [/Pegomastax/i, 'pegomastax'],
  [/Raptor/i, 'raptor'],
  [/TRex|T_Rex|Rex_Character/i, 'rex'],
  [/Spinosaur|Spino_/i, 'spino'],
  [/Stegosaur/i, 'stegosaurus'],
  [/Therizino/i, 'therizinosaur'],
  [/Titanosaur/i, 'titanosaur'],
  [/Triceratops/i, 'triceratops'],
  [/Troodon/i, 'troodon'],
  [/Yutyrannus/i, 'yutyrannus'],
  [/Astrocetus/i, 'astrocetus'],
  [/Astrodelphis/i, 'astrodelphis'],
  [/Basilisk/i, 'basilisk'],
  [/Bloodstalker/i, 'bloodstalker'],
  [/Bulbdog/i, 'bulbdog'],
  [/CrystalWyvern/i, 'crystal_wyvern'],
  [/Deathworm/i, 'deathworm'],
  [/FeatherLight/i, 'featherlight'],
  [/Fenrir/i, 'fenrir'],
  [/Ferox/i, 'ferox'],
  [/Gacha/i, 'gacha'],
  [/Gasbags/i, 'gasbags'],
  [/Glowtail/i, 'glowtail'],
  [/Griffin/i, 'griffin'],
  [/InsectSwarm/i, 'insect_swarm'],
  [/CaveCrab|Karkinos/i, 'karkinos'],
  [/Macrophage/i, 'macrophage'],
  [/Maewing/i, 'maewing'],
  [/Magmasaur/i, 'magmasaur'],
  [/Managarmr/i, 'managarmr'],
  [/Megachelon/i, 'megachelon'],
  [/Morellatops/i, 'morellatops'],
  [/Nameless/i, 'nameless'],
  [/Noglin/i, 'noglin'],
  [/ParakeetFishSchool|FishSchool/i, 'parakeet_fish_school'],
  [/Phoenix/i, 'phoenix'],
  [/Ravager/i, 'ravager'],
  [/Reaper/i, 'reaper'],
  [/RockDrake/i, 'rock_drake'],
  [/RockGolem|RockElemental/i, 'rock_elemental'],
  [/Seeker/i, 'seeker'],
  [/Shadowmane/i, 'shadowmane'],
  [/Shinehorn/i, 'shinehorn'],
  [/SnowOwl/i, 'snow_owl'],
  [/Spindles/i, 'velonasaur'], // Velonasaur uses "Spindles" in blueprint
  [/Summoner/i, 'summoner'],
  [/Unicorn/i, 'unicorn'],
  [/Equus/i, 'equus'],
  [/Wyvern/i, 'wyvern'],
  // Newly scraped creatures
  [/Argent(?:avis)?/i, 'argentavis'],
  [/Dimorphodon/i, 'dimorphodon'],
  [/Fjordhawk/i, 'fjordhawk'],
  [/Hesperornis/i, 'hesperornis'],
  [/Ichthyornis/i, 'ichthyornis'],
  [/Kairuku/i, 'kairuku'],
  [/Pelagornis/i, 'pelagornis'],
  [/Pteranodon/i, 'pteranodon'],
  [/Quetzal/i, 'quetzal'],
  [/Sinomacrops/i, 'sinomacrops'],
  [/Tapejara/i, 'tapejara'],
  [/TerrorBird/i, 'terror_bird'],
  [/Tropeognathus/i, 'tropeognathus'],
  [/Vulture/i, 'vulture'],
  [/Andrewsarchus/i, 'andrewsarchus'],
  [/Castoroides/i, 'castoroides'],
  [/Chalico(?:therium)?/i, 'chalicotherium'],
  [/Daeodon/i, 'daeodon'],
  [/Deinotherium/i, 'deinotherium'],
  [/DireBear|Direbear/i, 'dire_bear'],
  [/Direwolf/i, 'direwolf'],
  [/Hyaenodon/i, 'hyaenodon'],
  [/Jerboa/i, 'jerboa'],
  [/Lystrosaurus/i, 'lystrosaurus'],
  [/Mammoth/i, 'mammoth'],
  [/Mesopithecus/i, 'mesopithecus'],
  [/Otter/i, 'otter'],
  [/\bOvis\b/i, 'ovis'],
  [/Paraceratherium|Paracer_/i, 'paraceratherium'],
  [/Phiomia/i, 'phiomia'],
  [/Procoptodon/i, 'procoptodon'],
  [/Purlovia/i, 'purlovia'],
  [/WoollyRhino|Woolly_Rhino/i, 'woolly_rhino'],
  [/Thylacoleo/i, 'thylacoleo'],
  [/Beelzebufo/i, 'beelzebufo'],
  [/Carbonemys/i, 'carbonemys'],
  [/Ceratosaurus/i, 'ceratosaurus'],
  [/Deinosuchus/i, 'deinosuchus'],
  [/Diplocaulus/i, 'diplocaulus'],
  [/Sarcosuchus|Sarco_/i, 'sarco'],
  [/Angler(?:fish)?/i, 'anglerfish'],
  [/Basilosaurus/i, 'basilosaurus'],
  [/Chrysaora/i, 'chrysaora'],
  [/Cnidaria/i, 'cnidaria'],
  [/Coelacanth/i, 'coelacanth'],
  [/Dunkleosteus/i, 'dunkleosteus'],
  [/Electrophorus/i, 'electrophorus'],
  [/Eurypterid/i, 'eurypterid'],
  [/Helicoprion/i, 'helicoprion'],
  [/Ichthyosaurus/i, 'ichthyosaurus'],
  [/Leedsichthys/i, 'leedsichthys'],
  [/Liopleurodon/i, 'liopleurodon'],
  [/\bManta\b/i, 'manta'],
  [/Megalodon/i, 'megalodon'],
  [/Mosasaurus/i, 'mosasaurus'],
  [/Piranha/i, 'piranha'],
  [/Plesiosaur/i, 'plesiosaur'],
  [/SabertoothSalmon/i, 'sabertooth_salmon'],
  [/Tusoteuthis/i, 'tusoteuthis'],
  [/Achatina/i, 'achatina'],
  [/Ammonite/i, 'ammonite'],
  [/Arthropluera/i, 'arthropluera'],
  [/GiantBee|Giant_Bee/i, 'giant_bee'],
  [/Glowbug/i, 'glowbug'],
  [/JugBug/i, 'jug_bug'],
  [/Lamprey/i, 'lamprey'],
  [/\bLeech\b/i, 'leech'],
  [/Lymantria/i, 'lymantria'],
  [/Meganeura/i, 'meganeura'],
  [/\bOnyc\b/i, 'onyc'],
  [/Pulmonoscorpius/i, 'pulmonoscorpius'],
  [/Titanomyrma/i, 'titanomyrma'],
  [/Trilobite/i, 'trilobite'],
  [/Cryolophosaurus/i, 'cryolophosaurus'],
  [/Desmodus/i, 'desmodus'],
  [/Dimetrodon/i, 'dimetrodon'],
  [/Dinopithecus/i, 'dinopithecus'],
  [/\bDodo\b/i, 'dodo'],
  [/Doedicurus/i, 'doedicurus'],
  [/DungBeetle|Dung_Beetle/i, 'dung_beetle'],
  [/Fasolasuchus/i, 'fasolasuchus'],
  [/Kaprosuchus/i, 'kaprosuchus'],
  [/Maeguana/i, 'maeguana'],
  [/\bMantis\b/i, 'mantis'],
  [/Megalania/i, 'megalania'],
  [/Megaloceros/i, 'megaloceros'],
  [/Megatherium/i, 'megatherium'],
  [/RollRat|Roll_Rat/i, 'roll_rat'],
  [/Sabertooth(?!Salmon)/i, 'sabertooth'],
  [/ThornyDragon|Thorny_Dragon/i, 'thorny_dragon'],
  [/Titanoboa/i, 'titanoboa'],
  [/Archelon/i, 'archelon'],
  [/Malwyn/i, 'malwyn'],
  [/Rhyniognatha/i, 'rhyniognatha'],
  [/YiLing/i, 'yi_ling']
]

// ─── Public API ────────────────────────────────────────────────────────────────

/**
 * Resolve a Gigasaurus API slug from ARK's DinoNameTag and DinoClass fields.
 * Returns null when the creature isn't in the API.
 */
export function resolveSlug(dinoNameTag: string, dinoClass: string): string | null {
  // 1. Exact match on name tag
  if (NAME_TAG_MAP[dinoNameTag]) return NAME_TAG_MAP[dinoNameTag]

  // 2. Case-insensitive name tag match
  const tagLower = dinoNameTag.toLowerCase()
  for (const [key, slug] of Object.entries(NAME_TAG_MAP)) {
    if (key.toLowerCase() === tagLower) return slug
  }

  // 3. Blueprint class path fragments
  for (const [pattern, slug] of CLASS_FRAGMENT_MAP) {
    if (pattern.test(dinoClass)) return slug
  }

  return null
}

/**
 * Derive a display name for the creature.
 * Uses TamedName if set, otherwise formats the DinoNameTag.
 */
export function deriveDisplayName(tamedName: string, dinoNameTag: string): string {
  if (tamedName.trim()) return tamedName.trim()
  // Convert tag like "CeratosaurusAA" or "DeinosuchusAA" to readable form
  return dinoNameTag.replace(/AA$/, '').replace(/([A-Z])/g, ' $1').trim()
}
